// Command implementations
pub mod ctx;
pub mod debug;
pub mod describe;
pub mod events;
pub mod exec;
pub mod forward;
pub mod list;
pub mod logs;
pub mod multilogs;
pub mod plugin;
pub mod restart;
pub mod shell;
pub mod top;
pub mod watch;

// Re-export all command functions
pub use ctx::switch_context;
pub use debug::debug_pod;
pub use describe::describe_pod;
pub use events::show_events;
pub use exec::exec_pod;
pub use forward::port_forward;
pub use list::list_pods;
pub use logs::show_logs;
pub use multilogs::multi_logs;
pub use plugin::run_plugin;
pub use restart::restart_pod;
pub use shell::shell_pod;
pub use top::show_top;
pub use watch::watch_pods;
